### PR TITLE
Fixes  #119 and bug for no error msg when next step missing

### LINKED ISSUE #119: Change Lookup Logic for flow_engine.create_flow
See updated comments in package.
1. Pick released
2. pick version '0' status 'draft'
3. throw exception

### PR DESCRIPTION
**Pull request by rallen2010**

### CODE REVIEW

File: src/ddl/install_scratch.sql [hunk 1]
```diff
@@ -35,8 +35,8 @@ CREATE TABLE flow_diagrams (
         GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE )
     NOT NULL,
     dgrm_name     VARCHAR2(150 CHAR) NOT NULL,
-    dgrm_version  VARCHAR2(10 CHAR),
-    dgrm_status   VARCHAR2(10 CHAR),
+    dgrm_version  VARCHAR2(10 CHAR) DEFAULT '0' NOT NULL,
+    dgrm_status   VARCHAR2(10 CHAR) DEFAULT 'draft' NOT NULL,
     dgrm_category VARCHAR2(30 CHAR),
     dgrm_last_update TIMESTAMP WITH TIME ZONE DEFAULT systimestamp NOT NULL,
```
Comment (commi235) [inline src/ddl/install_scratch.sql:41]: Question:
Do we always use timestamp with timezone or always without?

**Review by commi235 — COMMENTED** [review]
Let us clarify general timestamp handling

File: src/ddl/install_scratch.sql (hunk 1 above)
Comment (rallen2010) [reply src/ddl/install_scratch.sql:41]: I was thinking that maybe we could just use date for diagram changes and meta-process level things, but should use timestamp for process runtime date fields? (We use DATE for the subflow_log - which should be a timestamp!)  We use timestamp with timezone everywhere else.  So I'd go for either just Date or 'with timezone' like everywhere else.

**Review by commi235 — APPROVED** [review]
